const $=s=>document.querySelector(s);let me=null,lang=localStorage.getItem('diskoko-dashboard-lang')||'ar',capacity=1;
const dict={ar:{empty:'لا توجد مشاريع بعد. أنشئ عالمك الأول.',linked:'مرتبط بسيرفر',unlinked:'غير مرتبط بسيرفر بعد',openStudio:'فتح في الاستوديو',draft:'مسودة',deployed:'نشط',paused:'متوقف',updated:'آخر تحديث',server:'السيرفر',noServers:'لم نجد سيرفرات قابلة للإدارة في حسابك.',connected:'الاتصال يعمل',connectedText:'تم العثور على سيرفرات تملكها أو تديرها.',noConnection:'لا توجد سيرفرات مرتبطة',noConnectionText:'اربط حساب Discord الذي يملك صلاحية إدارة السيرفر.',accountActive:'نشط',trial:'تجريبية',serversAvailable:'السيرفرات المتاحة',installed:'البوت مثبت',installRequired:'يحتاج تثبيت البوت',verify:'تحقق',install:'تثبيت Diskoko',verifying:'جارٍ التحقق…'},en:{empty:'No projects yet. Create your first world.',linked:'Linked to server',unlinked:'Not linked to a server yet',openStudio:'Open in Studio',draft:'Draft',deployed:'Live',paused:'Paused',updated:'Last updated',server:'Server',noServers:'No manageable servers were found.',connected:'Connection is live',connectedText:'Servers you own or manage are available.',noConnection:'No servers connected',noConnectionText:'Connect a Discord account with server management permissions.',accountActive:'Active',trial:'Trial',serversAvailable:'Available servers',installed:'Bot installed',installRequired:'Bot installation required',verify:'Verify',install:'Install Diskoko',verifying:'Verifying…'}};
function applyLang(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';const t=$('#languageToggle');if(t)t.textContent=lang==='ar'?'English':'العربية';renderProjects(window.projects||[]);renderServers(window.guilds||[])}
function prepareLoginLinks(){const target=new URLSearchParams(location.search).get('returnTo');if(!target)return;const encoded=encodeURIComponent(target);if($('#discordLogin'))$('#discordLogin').href=`/auth/discord?returnTo=${encoded}`;if($('#googleLogin'))$('#googleLogin').href=`/auth/google?returnTo=${encoded}`}
async function api(url,options){const r=await fetch(url,{headers:{'Content-Type':'application/json'},credentials:'include',...options});if(!r.ok){let body={};try{body=await r.json()}catch{}throw new Error(body.error||'تعذر إكمال الطلب')}return r.json()}
function setText(selector,value){const node=$(selector);if(node)node.textContent=value}
function planCapacity(plan){return {trial:1,starter:1,growth:3,complete:5}[plan]||1}
function escapeHtml(v){const d=document.createElement('div');d.textContent=v??'';return d.innerHTML}
function formatDate(value){if(!value)return '—';return new Date(value).toLocaleDateString(lang==='ar'?'ar-SA':'en-US',{year:'numeric',month:'short',day:'numeric'})}
async function installGuild(guildId){const data=await api(`/api/guilds/${encodeURIComponent(guildId)}/install-url`);const popup=window.open(data.url,'_blank','noopener,noreferrer');if(!popup)location.href=data.url}
async function verifyGuild(guildId,button){button.disabled=true;button.textContent=dict[lang].verifying;try{await api(`/api/guilds/${encodeURIComponent(guildId)}/connection/verify`,{method:'POST'});await refresh()}catch(e){alert(e.message)}finally{button.disabled=false}}
async function load(){prepareLoginLinks();const data=await api('/api/me');if(!data.user){$('#login').classList.remove('hidden');return}me=data.user;capacity=planCapacity(me.plan);$('#app').classList.remove('hidden');setText('#displayName',me.displayName||me.username);if($('#avatar'))$('#avatar').src=me.avatar||'';setText('#plan',me.plan.toUpperCase());setText('#planName',me.plan.toUpperCase());setText('#planRenewal',me.plan==='trial'?dict[lang].trial:'اشتراك نشط');setText('#accountStatus',me.status==='active'?dict[lang].accountActive:me.status);const [{projects},{guilds}]=await Promise.all([api('/api/projects'),api('/api/guilds').catch(()=>({guilds:[]}))]);window.projects=projects;window.guilds=guilds;updateSummary();applyLang()}
function updateSummary(){const projects=window.projects||[],guilds=window.guilds||[],linked=projects.filter(p=>p.guild_id).length,used=Math.max(linked,guilds.length);setText('#projectCount',projects.length);setText('#serverCount',`${used} / ${capacity}`);setText('#capacityLabel',`${Math.min(used,capacity)} / ${capacity}`);if($('#capacityBar'))$('#capacityBar').style.width=`${Math.min(100,Math.round(used/capacity*100))}%`;setText('#serverCountNote',guilds.length?`${guilds.length} سيرفر قابل للإدارة`:'حسب خطتك الحالية');setText('#connectionTitle',guilds.length?dict[lang].connected:dict[lang].noConnection);setText('#connectionText',guilds.length?dict[lang].connectedText:dict[lang].noConnectionText)}
function renderServers(guilds){const grid=$('#serverGrid');if(!grid)return;grid.innerHTML=guilds.length?guilds.map(g=>{const installed=g.connection?.install_status==='installed';return `<article class="server-card"><div class="server-avatar">${g.icon?`<img src="https://cdn.discordapp.com/icons/${encodeURIComponent(g.id)}/${encodeURIComponent(g.icon)}.png?size=96" alt="">`:'◈'}</div><div class="server-info"><h3>${escapeHtml(g.name)}</h3><p>${g.owner?'مالك السيرفر':'صلاحية إدارة'} · ${installed?dict[lang].installed:dict[lang].installRequired}</p><small>ID: ${escapeHtml(g.id)}</small></div><span class="server-state ${installed?'is-installed':'is-pending'}"><i></i>${installed?dict[lang].installed:dict[lang].installRequired}</span><div class="server-actions"><button class="btn primary install-guild" data-guild="${escapeHtml(g.id)}">${installed?'إعادة تثبيت / إدارة الربط':dict[lang].install}</button><button class="btn verify-guild" data-guild="${escapeHtml(g.id)}">${dict[lang].verify}</button><a class="btn" href="/studio?guild=${encodeURIComponent(g.id)}#dashboard">${dict[lang].openStudio} <span>←</span></a></div></article>`}).join(''):`<div class="empty server-empty"><span class="empty-icon">◈</span><b>${dict[lang].noServers}</b><small>${dict[lang].noConnectionText}</small></div>`;grid.querySelectorAll('.install-guild').forEach(b=>b.onclick=()=>installGuild(b.dataset.guild).catch(e=>alert(e.message)));grid.querySelectorAll('.verify-guild').forEach(b=>b.onclick=()=>verifyGuild(b.dataset.guild,b))}
function statusMeta(status){return {deployed:['deployed','نشط'],paused:['paused','متوقف'],draft:['draft','مسودة']}[status]||['draft',status||'مسودة']}
function renderProjects(projects){const d=dict[lang],grid=$('#projectGrid');if(!grid)return;grid.innerHTML=projects.length?projects.map(p=>{const [cls,label]=statusMeta(p.deployment_status);return `<article class="card project project-detail"><div class="project-top"><span class="badge ${cls==='deployed'?'ok':cls==='paused'?'stop':''}"><i></i>${label}</span><small>${d.updated}: ${formatDate(p.updated_at||p.updatedAt)}</small></div><h3>${escapeHtml(p.name)}</h3><p class="project-server">${p.guild_id?`<span>◈</span> ${d.linked}: <b>${escapeHtml(p.guild_id)}</b>`:`<span>○</span> ${d.unlinked}`}</p><div class="project-footer"><span>${d.server}: ${p.guild_id?'متصل':'غير متصل'}</span><a class="btn" href="/studio#dashboard">${d.openStudio} <span>←</span></a></div></article>`}).join(''):`<div class="empty"><b>${d.empty}</b></div>`}
async function refresh(){setText('#connectionTitle','جارٍ تحديث الحالة…');try{const [{projects},{guilds}]=await Promise.all([api('/api/projects'),api('/api/guilds').catch(()=>({guilds:[]}))]);window.projects=projects;window.guilds=guilds;updateSummary();applyLang()}catch(e){setText('#connectionTitle','تعذر تحديث الحالة');console.error(e)}}
$('#refreshServers')?.addEventListener('click',refresh);$('#logout')?.addEventListener('click',async()=>{await api('/api/logout',{method:'POST'});location.reload()});$('#newProject')?.addEventListener('click',async()=>{const name=prompt(lang==='ar'?'اسم المشروع':'Project name',lang==='ar'?'عالمي الجديد':'My new world');if(!name)return;await api('/api/projects',{method:'POST',body:JSON.stringify({name,design:{}})});await refresh()});load().catch(e=>{$('#login')?.classList.remove('hidden');console.error(e)});
