const $=s=>document.querySelector(s);let me=null,lang=localStorage.getItem('diskoko-dashboard-lang')||'ar';
const dict={ar:{empty:'لا توجد مشاريع بعد. أنشئ عالمك الأول.',linked:'مرتبط بسيرفر',unlinked:'غير مرتبط بسيرفر بعد',openStudio:'فتح الاستوديو'},en:{empty:'No projects yet. Create your first world.',linked:'Linked to server',unlinked:'Not linked to a server yet',openStudio:'Open Studio'}};
function applyLang(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';const t=$('#languageToggle');if(t)t.textContent=lang==='ar'?'English':'العربية';renderProjects(window.projects||[])}
async function api(url,options){const r=await fetch(url,{headers:{'Content-Type':'application/json'},credentials:'include',...options});if(!r.ok)throw new Error((await r.json()).error||'تعذر إكمال الطلب');return r.json()}
function setText(selector,value){const node=$(selector);if(node)node.textContent=value}
async function load(){const data=await api('/api/me');if(!data.user){$('#login').classList.remove('hidden');return}me=data.user;$('#app').classList.remove('hidden');setText('#displayName',me.displayName||me.username);if($('#avatar'))$('#avatar').src=me.avatar||'';setText('#plan',me.plan.toUpperCase());setText('#planName',me.plan.toUpperCase());const capacity={trial:1,starter:1,growth:3,complete:5}[me.plan]||1;const {projects}=await api('/api/projects');window.projects=projects;setText('#projectCount',projects.length);setText('#serverCapacity',`${projects.filter(p=>p.guild_id).length} / ${capacity}`);setText('#usage',`${Math.min(99,Math.round(projects.length/capacity*100))}%`);renderProjects(projects);applyLang()}
function renderProjects(projects){const d=dict[lang],grid=$('#projectGrid');if(!grid)return;grid.innerHTML=projects.length?projects.map(p=>`<article class="card project"><span class="badge ${p.deployment_status==='deployed'?'ok':''}">${escapeHtml(p.deployment_status)}</span><h3>${escapeHtml(p.name)}</h3><p>${p.guild_id?`${d.linked}: ${escapeHtml(p.guild_id)}`:d.unlinked}</p><a class="btn" href="/#dashboard">${d.openStudio}</a></article>`).join(''):`<div class="empty">${d.empty}</div>`}
function escapeHtml(v){const d=document.createElement('div');d.textContent=v||'';return d.innerHTML}
$('#languageToggle')?.addEventListener('click',()=>{lang=lang==='ar'?'en':'ar';localStorage.setItem('diskoko-dashboard-lang',lang);applyLang()});$('#logout')?.addEventListener('click',async()=>{await api('/api/logout',{method:'POST'});location.reload()});$('#newProject')?.addEventListener('click',async()=>{const name=prompt(lang==='ar'?'اسم المشروع':'Project name',lang==='ar'?'عالمي الجديد':'My new world');if(!name)return;await api('/api/projects',{method:'POST',body:JSON.stringify({name,design:{}})});load()});load().catch(e=>{$('#login')?.classList.remove('hidden');console.error(e)});
