const $=s=>document.querySelector(s);let state=null,lang=localStorage.getItem('diskoko-dashboard-lang')||'ar';
const dict={ar:{installed:'البوت مثبت',notConnected:'البوت غير مربوط',installRequired:'يحتاج تثبيت البوت',verify:'تحقق الآن',install:'تثبيت Diskoko',openStudio:'فتح Studio',verifying:'جارٍ التحقق…',connected:'متصل',active:'نشطة',trial:'تجريبية',noServers:'لا توجد سيرفرات في هذه الفئة بعد.',days:'يوم',expired:'منتهية',never:'غير محددة'},en:{installed:'Bot installed',notConnected:'Bot not connected',installRequired:'Bot installation required',verify:'Verify now',install:'Install Diskoko',openStudio:'Open Studio',verifying:'Verifying…',connected:'Connected',active:'Active',trial:'Trial',noServers:'No servers in this group yet.',days:'days',expired:'Expired',never:'Not specified'}};
const t=k=>dict[lang][k]||k;const esc=v=>{const d=document.createElement('div');d.textContent=v??'';return d.innerHTML};
let csrfTokenPromise=null;async function csrf(){if(!csrfTokenPromise)csrfTokenPromise=fetch('/api/csrf-token',{credentials:'include'}).then(r=>r.json()).then(x=>x.token);return csrfTokenPromise}
async function api(url,options={}){const method=String(options.method||'GET').toUpperCase(),headers={'Content-Type':'application/json',...(options.headers||{})};if(['POST','PUT','PATCH','DELETE'].includes(method))headers['X-CSRF-Token']=await csrf();const r=await fetch(url,{...options,method,headers,credentials:'include'});let body={};try{body=await r.json()}catch{}if(!r.ok)throw new Error(body.error||'تعذر إكمال الطلب');return body}
function formatDate(v){if(!v)return t('never');return new Date(v).toLocaleDateString(lang==='ar'?'ar-SA':'en-US',{year:'numeric',month:'short',day:'numeric'})}
function remaining(v){if(!v)return null;return Math.ceil((new Date(v)-Date.now())/86400000)}
function planCapacity(plan){return {trial:1,starter:1,growth:3,complete:5}[plan]||1}
function prepareLoginLinks(){const target=new URLSearchParams(location.search).get('returnTo');if(!target)return;const encoded=encodeURIComponent(target);$('#discordLogin')?.setAttribute('href',`/auth/discord?returnTo=${encoded}`);$('#googleLogin')?.setAttribute('href',`/auth/google?returnTo=${encoded}`)}
function planName(plan){return String(plan||'trial').toUpperCase()}
function renderServerCard(server,linked){const c=server.connection||{};const installed=c.install_status==='installed';const status=linked?'installed':'not_connected';return `<article class="personal-server-card ${linked?'is-linked':'is-unlinked'}"><div class="personal-server-top"><span class="personal-server-avatar">${server.icon?`<img src="https://cdn.discordapp.com/icons/${encodeURIComponent(server.id)}/${encodeURIComponent(server.icon)}.png?size=96" alt="">`:'◈'}</span><span class="server-state-label ${linked?'ready':'pending'}"><i></i>${linked?t('installed'):t('notConnected')}</span></div><h3>${esc(server.name)}</h3><p>${server.owner?'مالك السيرفر':'لديك صلاحية إدارته'} · ${linked?'تم التحقق':'لم يتم تثبيت البوت'}</p><small class="server-id">ID: ${esc(server.id)}</small><div class="personal-server-actions">${linked?`<a class="btn primary" href="/studio?guild=${encodeURIComponent(server.id)}#overview">${t('openStudio')} ↗</a><button class="btn verify-guild" data-guild="${esc(server.id)}">${t('verify')}</button>`:`<button class="btn primary install-guild" data-guild="${esc(server.id)}">${t('install')}</button><button class="btn verify-guild" data-guild="${esc(server.id)}">${t('verify')}</button>`}</div></article>`}
function renderServers(){const servers=state.servers||[],linked=servers.filter(s=>s.connection?.install_status==='installed'),unlinked=servers.filter(s=>s.connection?.install_status!=='installed');$('#linkedServers').innerHTML=linked.map(s=>renderServerCard(s,true)).join('')||`<div class="personal-empty">${t('noServers')}</div>`;$('#unlinkedServers').innerHTML=unlinked.map(s=>renderServerCard(s,false)).join('')||`<div class="personal-empty">${t('noServers')}</div>`;$('#linkedCount').textContent=linked.length;$('#unlinkedCount').textContent=unlinked.length;$('#availableCount').textContent=servers.length;$('#linkedTitle').textContent=`${linked.length} ${lang==='ar'?'سيرفر مرتبط':'linked servers'}`;$('#unlinkedTitle').textContent=`${unlinked.length} ${lang==='ar'?'سيرفر غير مربوط':'unlinked servers'}`;const cap=state.limits?.servers||planCapacity(state.plan?.plan);const used=linked.length;$('#capacityLabel').textContent=`${used} / ${cap}`;$('#capacityLargeLabel').textContent=`${used} / ${cap} ${lang==='ar'?'مستخدمة':'used'}`;$('#capacityBar').style.width=`${Math.min(100,used/cap*100)}%`;$('#capacityLargeBar').style.width=`${Math.min(100,used/cap*100)}%`;document.querySelectorAll('.install-guild').forEach(b=>b.onclick=()=>installGuild(b.dataset.guild));document.querySelectorAll('.verify-guild').forEach(b=>b.onclick=()=>verifyGuild(b.dataset.guild,b))}
function renderSubscription(){const p=state.plan||{},plan=p.plan||state.user.plan,days=remaining(p.current_period_end);$('#planChip').textContent=planName(plan);$('#subscriptionPlan').textContent=planName(plan);$('#subscriptionStatus').textContent=plan==='trial'?t('trial'):(p.status||t('active'));$('#subscriptionStart').textContent=formatDate(p.created_at||state.user.createdAt);$('#subscriptionEnd').textContent=formatDate(p.current_period_end);$('#subscriptionState').textContent=days===null?t('active'):(days<0?t('expired'):t('active'));$('#daysRemaining').textContent=days===null?'∞':Math.max(0,days);$('#expiryNote').textContent=days===null?t('never'):`${lang==='ar'?'حتى':'until'} ${formatDate(p.current_period_end)}`;$('#subscriptionCapacity').textContent=`${state.limits?.servers||planCapacity(plan)} ${lang==='ar'?'سيرفر':'servers'}`;$('#subscriptionCapacity').nextElementSibling.textContent=lang==='ar'?'السيرفرات المسموح ربطها حسب خطتك الحالية.':'Servers allowed by your current plan.'}
function renderAccount(){const u=state.user;$('#displayName').textContent=u.displayName||u.username;$('#settingsName').textContent=u.displayName||u.username;$('#settingsEmail').textContent=u.email||'غير متاح';$('#settingsLanguage').textContent=lang==='ar'?'العربية':'English';$('#avatar').src=u.avatar||'';$('#healthLabel').textContent=state.servers?.length?`● ${lang==='ar'?'تم الفحص':'Checked'}`:'—';$('#healthText').textContent=state.servers?.length?`${state.servers.length} ${lang==='ar'?'سيرفر قابل للمراجعة':'servers available'}`:t('noServers');$('#overviewText').textContent=state.servers?.length?`لديك ${state.servers.length} سيرفر قابل للإدارة. ${state.servers.filter(s=>s.connection?.install_status==='installed').length} منها مربوط وجاهز، والبقية تحتاج إجراء.`:'لم نجد سيرفرات قابلة للإدارة في حسابك.';renderSubscription();renderServers()}
async function installGuild(id){const popup=window.open('about:blank','_blank');try{const d=await api(`/api/guilds/${encodeURIComponent(id)}/install-url`);if(popup&&!popup.closed)popup.location.href=d.url;else location.href=d.url}catch(e){popup?.close();alert(e.message)}}
async function verifyGuild(id,button){button.disabled=true;button.textContent=t('verifying');try{await api(`/api/guilds/${encodeURIComponent(id)}/connection/verify`,{method:'POST'});await loadAccount()}catch(e){alert(e.message)}finally{button.disabled=false}}
async function loadAccount(){try{state=await api('/api/account/overview');$('#login').classList.add('hidden');$('#app').classList.remove('hidden');renderAccount()}catch(e){if(e.message==='يلزم تسجيل الدخول'){$('#login').classList.remove('hidden');$('#app').classList.add('hidden')}else console.error(e)}}
function bind(){document.querySelectorAll('[data-scroll]').forEach(a=>a.onclick=()=>{document.querySelector(a.getAttribute('href'))?.scrollIntoView({behavior:'smooth'});document.querySelectorAll('[data-scroll]').forEach(x=>x.classList.remove('active'));a.classList.add('active')});$('#refreshAccount')?.addEventListener('click',loadAccount);$('#refreshServers')?.addEventListener('click',loadAccount);const logout=async()=>{await api('/api/logout',{method:'POST'});location.reload()};$('#logout')?.addEventListener('click',logout);$('#logoutSettings')?.addEventListener('click',logout);$('#editDisplayName')?.addEventListener('click',()=>alert('اسم العرض يتبع حساب Discord أو Google في هذه المرحلة. يمكن تعديل اسم السيرفر من Studio.'));$('#copyEmail')?.addEventListener('click',()=>{if(state?.user?.email)navigator.clipboard?.writeText(state.user.email)});$('#languageToggle')?.addEventListener('click',()=>{lang=lang==='ar'?'en':'ar';localStorage.setItem('diskoko-dashboard-lang',lang);location.reload()})}
prepareLoginLinks();bind();loadAccount();
